<div class="page-header">
    <h2>Predicting stock growth
    <small><?php echo handle_to_date($_GET['id']); ?></small></h2>
</div>
<div class="media">
    <?php
    /*Easy availability of financial data, advances in computational
    techniques for pattern recognition and optimization, insightful
    formulas for asset pricing, and the capacity
    to analyse increasingly large quantities of data have led to a
    boom in recent decades in the field of computational finance.*/
    ?>
    <p>Some co-conspirators and I have been experimenting with the application of computational
    techniques such as machine learning and genetic programming to quantitative
    finance. We're trying to use these techniques to develop "optimal"
    investment strategies. Investment portfolios are optimized with
    regard to two metrics: growth and risk. An optimal investment strategy maximizes growth
    while minimizing risk, but the goals of maximizing growth and minimizing risk often compete.
    A portfolio which maximizes expected growth is often riskier than
    portfolios with less aggressive growth expectations. Here, however,
    I <em>won't</em> be concerned with the often conflicting relationship between
    these two optimization goals. I'll be discussing only the work
    we've done toward <em>predicting growth</em>. 
    While there are well-known techniques for
    assessing and minimizing risk (volatility of a risky asset), predicting
    growth is very much an open problem. It is the main problem we've been
    working on and the one I'll be discussing here.</p>

    <p>Machine learning has been used for pattern recognition 
    with an astonishing degree of success in a wide range of contexts. Fairly simple algorithms
    yield over 90% accuracy in recognizing hand-written digits, and other algorithms
    make it possible to classify object types within digital images
    and to identify individuals through facial recognition. 
    But predicting market prices of publicly traded
    equities proves to be somewhat more difficult because price behavior is subject to
    significant unforeseeable fluctuations, or <em>noise</em>. After many failed and some
    partially successful experiments, 
    we have, however, developed a technique for predicting growth with "a reasonably
    high degree of accuracy." I'll discuss later in statistical terms
    what <em>accuracy</em> in this context means exactly. And, while the details of our algorithm are proprietary,
    I can also share a few of our results and discuss their significance and their limitations.</p>
    
    <p>To illustrate our results more concretely, let me begin with a chart. I'll try
    over the course of this article to explain more clearly what the chart
    means and how the data underlying such charts can be used.
    <img src="images/ge_growth.png" class="img-responsive">
    We see here <span style="color:blue">actual adjusted price (blue)</span> compared to <span style="color:red">predicted 
    growth (red)</span> for <em>GE</em> over the last 20 years.
    The upper portion of the chart simply plots values
    pulled from <a href="http://finance.yahoo.com" target="_blank">Yahoo! Finance</a>,
    which provides not only historical actual prices but also <em>adjusted closes</em> for equities 
    traded on the major exchanges. The <em>adjusted closes</em> are closing prices that have been re-calibrated to account
    for splits and dividends. Such adjustments are necessary to get an accurate
    picture of true return on investment, whether or not the stock has split and whether or not
    it pays a dividend.</p>

    <p>While the upper section of the chart shows adjusted close, the lower section
    plots <em>predicted growth</em>, which
    is generated by our machine learning algorithm using only information
    knowable <em>in real time</em>. The prediction made on August 30, 2010,
    for example, is based only on data that was already available at the time.
    Otherwise, we wouldn't be able to generalize to the present, the 
    point in time from which we are trying to make predictions about an unknown future.
    The prediction on any given day is derived only
    from information available up until that time, just as right now,
    we have access only to past facts and must use those facts to make
    intelligent hypotheses about what is likely to happen in the future.</p>

    <p>Looking more closely at the lower section of the chart, you should see
    a grey horizontal line at about <code>1.2</code>. This line represents <em>average</em> growth.
    So, the model is predicting above average growth whenever the red line
    is above the grey line and below average growth when the red line drops
    below the grey.</p>

    <p>What immediately jumps out at us on this chart is the spike in predicted growth
    in early 2009. While the model accurately identifies the crash
    of 2009 as a great time to buy, it would have been difficult
    <em>in real time</em> to recognize the exact best spot even with the help of the
    predictions. At any given point in time, we know only the predictions
    up to that point but not what the model will predict tomorrow or
    a month from now. We don't know future <em>predictions</em> any more than we know future <em>prices</em>.
    Relative to the average or to other equities, we can
    say that predicted growth is better or worse, but tomorrow it
    might be better still. We simply won't know until we have tomorrow's data to which to apply the model.
    For example, toward the
    end of 2008, predicted growth spikes first to around <code>1.6</code>, which translates
    to a predicted 60% return on investment over the prediction period.
    <em>In real time</em>, with knowledge only of events and metrics
    up to that point, that would already seem like a great spot to buy, and
    it would in fact have been a pretty good one, as long as you could
    hold onto your seat through the bottom of the crash. If you waited
    a little longer, however, until the stock went down another 50% to $5 in early 2009,
    you would have done significantly better. So, while our crystal ball
    provides useful information, a lot of work remains for determining how best to make
    use of the predictions <em>in real time</em> in an optimized investment strategy.</p>

    <p>I'll leave it at that for now as an introduction to our work on this problem.
    Before going into greater
    detail about the sense in which our predictions are accurate and the questions
    growing out of our analyses up to this point, I'd like to
    back up a bit and discuss some common pitfalls that we are studiously
    trying to avoid.</p>

    <h3>Optical illusions and the smugness of hindsight</h3>

    <p>I recently watched an online video that claimed to solve the same problem
    we are addressing: predicting growth. Its author 
    claimed to have found a hidden technique for predicting <em>with 100%
    accuracy</em> entry points for buying stocks low and exit points for 
    selling high. While I knew right away that the "100%" claim
    was at best an exaggeration, the author's idea sounded plausible,
    so I wrote some code to calculate and chart 
    entry and exit points according to this algorithm.
    The charts really did
    seem more often than not to mark sell points that were higher than
    the buy points. So, I backtested the algorithm on a 
    random selection of stocks from the S&P over a 20 year period.
    While the algorithm generated a profit on a statistically relevant set of data, one would
    have in fact made <em>more</em> money by just investing an equal share in each
    of the randomly selected stocks and selling at the end of the trial.
    In other words, buy and hold was superior to the algorithm.</p>

    <p>I tell this story mainly to emphasize how hard it is to beat
    buying and holding an index. Sure, you can look at some charts, find <em>in hindsight</em>
    the best buy and sell points, and then talk yourself into thinking
    there is a pattern that could have been spotted in advance. But this impression
    is almost invariably an <em>optical illusion</em> leading to what one might call the <em>smugness of hindsight</em>.
    Once we know what actually happened, our brains can't ignore that knowledge.
    So, when we look at past market data, we can't help but project patterns <em>in hindsight</em>
    onto the charts. That's just how our brains work. We are hardwired to see patterns
    in the world around us, but the patterns we see in stock charts generally prove to be optical
    illusions because we project current knowledge onto the past.
    Machines, on the other hand, don't suffer from the same smugness of hindsight:
    They can be programmed so that they really do (for purposes of backtesting)
    make use only of facts known at the time.
    But if you try to quantify and backtest <em>out of sample</em> (on data you haven't looked at yet)
    patterns created by <em>humans</em> with the benefit of hindsight,
    you'll find that they almost never hold up. They'll probably still make
    some money because the market as a whole has advanced. So even completely random entry
    and exit points can be expected to make money.
    But few algorithms can consistently beat buy and hold.
    When you sell at suboptimal exit points, as you sometimes will, you miss out on market upturns
    where the buy-and-hold strategist still makes a profit.</p>

    <p>Our goal is to develop an algorithmic investment system
    that really does perform demonstrably better than buy and hold. One component of this
    system is making accurate growth predictions. It is this component that we are currently
    working on and that the above chart illustrates. Our system is designed
    to look for patterns over periods of several months and not for intraday patterns useful for day
    trading. Most investors, including us, don't have the resources (such as fast fiber-optic
    feeds in close proximity to the exchanges) to compete
    with brokerages that receive market data within nanoseconds of its availability, so we have
    focussed on medium- to long-term patterns where it doesn't matter so much if your
    data feed is seconds or minutes behind the market. We're concerned with predicting
    how well a stock is likely to perform in the coming weeks and months. Let's look now
    at how to get a statistically valid measure for the accuracy of such predictions.</p>

    <h3>Making accurate predictions</h3>
    <p>Stock prices are influenced by many unpredictable factors and
    are thus subject to significant unforeseable fluctuations. From a predictive standpoint,
    such fluctuations are just <em>noise</em>. Because of it, we can never
    predict future prices exactly. 
    So, we need a measure by which to judge which of several inexact
    predictions is the best. <a href="https://en.wikipedia.org/wiki/Standard_error"
    target="_blank">Standard error</a> is the measure we are looking for to
    quantify predictive accuracy.
    The <em>standard error</em> of an estimate or prediction is the statistical
    counterpart to <em>standard deviation</em>. Information on <a href="https://en.wikipedia.org/wiki/Standard_error"
    target="_blank">how to calculate it</a>
    is readily available, so I won't go into that here. What standard error means, though,
    can be explained by a simple example: If we say that our predictions have a standard
    error of <code>0.2</code> relative to known actual values, that means that about 
    <code>2/3</code> of our estimates will be within <code>0.2</code> of the correct value.</p>
    
    <p>The success of a machine learning algorithm is measured, then, by low standard error <em>out
    of sample</em>--i.e., on test data not visited by the algorithm while it was
    learning the model. Machine learning algorithms are <em>designed</em> to minimize
    error <em>in sample</em>, on the data from which the model is developed.
    So, they will invariably do well in sample but will not necessarily be
    useful out of sample. What that means in our context is that we might 
    develop a model from past data on some random selection
    of stocks that makes very accurate predictions on <em>those</em> stocks for <em>that</em> time period.
    But its predictions may not be accurate out of sample,
    i.e., for different time periods or on stocks that were not used when developing the model.</p>

    <p>Our baseline for predicting growth was the mean, which can
    be shown to be the constant model with the greatest accuracy. In other words,
    our baseline was to take a random selection of equities and simply calculate 
    their average growth over a given forecast interval. The standard error
    of this constant prediction is then the value that needs to be beaten <em>out of sample</em>.
    Given the noisy fluctuations, this wasn't easy to do. As the basis for an investment strategy, 
    this baseline prediction will invariably lead to  
    <em>buy and hold</em>. The baseline prediction is in fact impossible to beat if
    it is true that current price alone is the best predictor of future price.
    As is well known among specialists in quantitative finance, buy
    and hold is hard to beat. Many experts believe that 
    efficient markets price in all available information. If their hypothesis 
    holds, current price 
    <em>is</em> in fact the best predictor of future price, and buy-and-hold is the best
    investment strategy.</p>
    <p>We have experimented with numerous technical
    indicators to determine which, if any, could lead to models consistently showing lower out-of-sample
    error than the baseline prediction, and we have arrived at features that
    have shown modest but consistent improvements relative to 
    the baseline. While the features and algorithms used in deriving predictions are proprietary information,
    I <em>can</em> share the growth predictions that have been made for past data.
    These predictions are illustrated in charts like the one shown above for GE prices
    and predicted growth over the last 20 years. Let's take a second look, then, at
    some charts in light of what we now know about the sense in which the
    predictions are "accurate" given the data available in real time.</p>
    
    <h3>Use and limitations of growth predictions</h3>
    <p>Let's first zoom in on the most interesting time frame from the 20-year GE chart
    we have already seen:</p>
    <img src="images/ge_growth_detail.png" class="img-responsive">
    <p>Here we are zooming in on the two years before and after the stock price bottomed
    out in early 2009.
    <?php
    // marker
    ?>

     While it may be difficult or impossible in real time to deduce from the predictions an optimal buy point,
    there is a clear spike in predicted growth which peaks at what is clearly
    the best time to <em>buy</em>. The predictions do not, however, provide comparable clarity
    on when to <em>sell</em>. When the stock is in reality about to drop from a peak of over 30
    the growth prediction is weak but still positive, somewhere around <code>1.1</code>.
    The algorithm expects the stock to do worse than the baseline at this point in time, but it
    is wrongly still predicting positive growth. According to the predictions,
    the stock's value would increase by 10% from, let's say, 30 to 33. Instead
    it drops from 30 to a low around 5. The predictions still beat the baseline,
    which constantly predicts a 20% increase in price, but the model
    doesn't seem willing to go out on a limb in predicting a catastrophic decline.</p>
    <p>When using these predictions in an investment strategy, one important
    question will be whether those stocks showing the highest predicted growth in
    bear markets are in fact fairly resistent to decline or are even among the few stocks that
    actually show a gain during a financial crisis. In that case, even fairly
    simple strategies built on the predictions should do quite well.
    This is the kind of question we're still researching, so for now, I don't
    yet have an answer.</p>

    <p>The chart of TSLA shows that the model doesn't predict explosive growth only
    after a sharp decline but also after a flat period. The model isn't catching <em>only</em>
    the patterns typical of stocks bottoming out as they did in early 2009:</p>
    <img src="images/tsla_growth.png" class="img-responsive">
    <p>Here, too, we see a spike in predicted growth at what would have been
    an excellent time to buy Tesla Motors, namely in May of 2013. Aside from the
    difficulty of taking action in real time, <em>without the knowledge of whether predicted
    growth might go higher still</em>, if we had invested in May 2013 when the stock was below
    100 and then sold in October when predicted growth falls back to the baseline, we would
    have had a return on investment of around 100% over a period of only 5 months!</p>

    <p>Idea of combing the market for stock with highest growth potential</p>
    <p>An interesting feature of this chart is that predicted growth actually <em>does</em>
    show a well-defined valley from December 2013 until roughly March 2014. The negative
    growth prediction does not, however, reflect what actually happens. In reality, TSLA
    still has a good deal of growth left and, while its price fluctuates quite a bit
    in the ensuing time period, it almost always stays above 200. So, the sell point
    indicated by the model is certainly sub-optimal.</p>

    <h3>Summary</h3>
    <p>Let me start with what our model <em>does not</em> do: It doesn't
    predict bull and bear cycles with anything approaching 100% accuracy. It is
    a model based on statistics and designed to yield the lowest possible standard
    error based on metrics known in real time. It can't predict fluctuations due
    to noise, which is just the aggregate of causally relevant events that could not be foreseen
    at the time. We required
    numerous attempts, trying many different metrics, to arrive at a model
    yielding predictions more accurate out of sample than the baseline of average
    growth. The charts shown here reflect the output of that model and suggest
    that these growth predictions can provide very useful input for investment strategies capable of
    outperforming buy and hold.</p>

</div>
